[package]
name = "nvim-ctrl"
version = "0.1.0"
authors = ["greg <gregory.mkv@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
neovim-lib = "0.6.1"
anyhow = "1.0.28"
structopt = "0.3.12"
